// This file was generated by Prisma
// Note: dotenv is not needed in production (Vercel injects env vars automatically)
// For migrations, Prisma will use DIRECT_URL if available, otherwise DATABASE_URL
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Use DIRECT_URL for migrations (direct connection, port 5432)
  // Falls back to DATABASE_URL if DIRECT_URL is not set
  datasource: {
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
